### PR TITLE
Index in template should start at 0

### PR DESCRIPTION
**Pull request by khaledkhalil94**
Index should be incremented after replacing the index of the item.

### CODE REVIEW

**Comment by petersirka** [comment]
Thank you! I have found another problem and it's fixed.
https://github.com/totaljs/components/commit/55368f7439a25415eb0182d8ea7548536ea74a15

__Now it works like a charm:__
https://componentator.com/components/j-repeatergroup/

Thank you!

**Comment by khaledkhalil94** [comment]
[55368f7](https://github.com/totaljs/components/commit/55368f7439a25415eb0182d8ea7548536ea74a15) caused an issue for me, it doesn't work with the following component
`<div data-jc="textbox" data-jc-path="params[$index].paramKey" data-jc-config="disabled:true;"></div>`

_I suppose this is the right way to bind a component value to another value in an array ?_

For this case, index should be incremented for all keys group, what you think ?

**Comment by petersirka** [comment]
Shit, yes you're right. I have fixed it :-D sorry and thank you.

**Comment by khaledkhalil94** [comment]
No problem, thanks for your collaboration :)

**Pull request merged**
