### PR TITLE
new component

### PR DESCRIPTION
**Pull request by PatchwerkQWER**
Avatar component for simple avatars

### CODE REVIEW

**Comment by petersirka** [comment]
Great!
I think it would be better to use `config` instead of `data-jc-` attributes.

- from `data-jc-username="Jane Doe"` to `data-jc-config="username:Jane Doe"`
- from `data-jc-image="useravatar.png"` to `data-jc-config="useravatar.png"`

What do you think about it?

**Comment by PatchwerkQWER** [comment]
I was trying use config for that but link doesn't work in that (maybe wrong split, not sure?) And for name... I think this looks much better (in this case)
```javascript
<div data-jc="avatar" data-jc-username=@{user.name} data-jc-config="rounded:false;lighten:255;background:#000000"></di
```
than
```javascript
<div data-jc="avatar" data-jc-config="username:@{user.name};rounded:false;lighten:255;background:#000000"></di
```
Or maybe it can have both variants.

And for links, this doesn't work:
```javascript
<div data-jc="avatar" data-jc-config="link:https://avatars3.githubusercontent.com/u/7585285?v=4&s=460;"></di
```
config.link is empty (so, maybe it's bug)

**Comment by petersirka** [comment]
There is need to add a backslash `\` but ... I'm going to update parsing of configuration in jComponent, give me 10 minutes.

**Comment by petersirka** [comment]
I have updated jComponent, now this will work:

```html
<div data-jc="avatar" data-jc-config="link:https://avatars3.githubusercontent.com/u/7585285?v=4&s=460"></div>
```

**Comment by PatchwerkQWER** [comment]
I fortgot that it should have backslash. My bad. That update - nice. I'll push update soon

**Comment by petersirka** [comment]
Great. BTW: I have updated a picture of your component.

**Pull request merged**
